import CurrencySalaryBonusQuestion from './CurrencySalaryBonus';
import SelectQuestion from './Select';
import OptionsQuestion from './Options';
import MonthYearQuestion from './MonthYear';
import PostcodeQuestion from './Postcode';
import FreeTextQuestion from './FreeText';
import MultiRangeQuestion from './MultiRange';
import NameQuestion from './Name';
import FullNameQuestion from './MultiName';
import PreUniQualificationQuestion from './PreUniQualification';
import LocationQuestion from './LocationVariableDetail';

export const CurrencySalaryBonus = CurrencySalaryBonusQuestion;
export const Select = SelectQuestion;
export const Options = OptionsQuestion;
export const MonthYear = MonthYearQuestion;
export const Postcode = PostcodeQuestion;
export const FreeText = FreeTextQuestion;
export const MultiRange = MultiRangeQuestion;
export const Name = NameQuestion;
export const FullName = FullNameQuestion;
export const PreUni = PreUniQualificationQuestion;
export const Location = LocationQuestion;
